version: '3.0'
services:
  consumer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: consumer
    ports:
      - "3001:3000"
    command: ["/bin/sh","-c","sleep infinity"]
    networks:
      - ourmind
    environment:
      NODE_ENV: development
    volumes:
      - .:/usr/app/consumer
networks:
  ourmind:
   driver: bridge
   name: ourmind-network
   attachable: true