version: '3.8'
services:
  zookeeper:
    image: zookeeper:3.6.3
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - ourmind
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    networks:
      - ourmind
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafkadrop:
    image: obsidiandynamics/kafdrop:latest
    container_name: kafkadrop
    ports:
      - "9000:9000"
    networks:
      - ourmind
    environment:
      KAFKA_BROKERCONNECT: kafka:9092
    depends_on:
      - kafka
networks:
  ourmind:
   driver: bridge
   name: ourmind-network
   attachable: true